# Generated by Django 4.2.7 on 2025-10-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Nombre único del entorno. Debe ser un URL slug.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Breve explicación de para qué sirve el entorno.', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del entorno')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del entorno')),
            ],
            options={
                'db_table': 'environments',
                'ordering': ['name'],
            },
        ),
    ]
