# QUITA esta línea: version: '3.8'

services:
  # Servicio de la base de datos PostgreSQL
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=configdb
      - POSTGRES_USER=configuser
      - POSTGRES_PASSWORD=configpass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U configuser -d configdb"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Servicio de la API Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://configuser:configpass@db:5432/configdb
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy

# Volumen para persistir datos de PostgreSQL
volumes:
  postgres_data: