# Generated by Django 4.2.7 on 2025-10-25 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Nombre único de la variable en un entorno. Debe ser un URL slug.', max_length=100)),
                ('value', models.TextField(help_text='Valor de la variable.')),
                ('description', models.TextField(blank=True, help_text='Breve explicación de para qué sirve la variable.', max_length=500, null=True)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Indica si es sensible (e.g., True para contraseñas)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la variable')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización de la variable')),
                ('environment', models.ForeignKey(help_text='Entorno al que pertenece esta variable', on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='environments.environment')),
            ],
            options={
                'db_table': 'variables',
                'ordering': ['name'],
                'unique_together': {('name', 'environment')},
            },
        ),
    ]
